### ISSUE TITLE
Should this article mention the number of trips thru the array?

### ISSUE THREAD

**Issue by dagonyclark** [learn-co-students/sorting-readme-prework#1]
Section ```The .sort method``` describes how two elements are compared at a time. For ```array = [7, 3, 1, 2, 6, 5]```, we're told the result of the first iteration will be ```[3, 7, 1, 2, 6, 5]```, and the second iteration will yield 7 and 1. 

By extending this logic, however, the result of these second iteration will be [3, 1, 7, 2, 6, 5] and subsequent iterations on a single trip through the array will give [3, 1, 2, 6, 5, 7]. There's no mention of how sort deals with numbers it's already passed. I assume this is done via multiple trips through the data, as a second trip through [3, 1, 2, 6, 5, 7] would result in the correct order. If so, or if it does something else entirely, it should be clarified.

**Comment by sgharms** [comment]
@dagonyclark The content as written is inaccurate. I've removed this misleading content.
